## Exercise 1

In [2]:
##  Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

import numpy as np
import pandas as pd

arr = np.arange(1, 11)
matrix = arr.reshape(2, 5)

print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## Exercise 2

In [4]:
## Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

arr = np.arange(1, 21)
extracted_elements = arr[5:16]

print(arr)
print(extracted_elements)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11 12 13 14 15 16]


## Exercise 3

In [5]:
## Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}.
# Then, add a new item to the series with the key 'pears' and the value 4.

fruits = {'apples': 3, 'bananas': 2, 'oranges': 1}
series = pd.Series(fruits)

series['pears'] = 4

print(series)


apples     3
bananas    2
oranges    1
pears      4
dtype: int64


## Exercise 4

In [7]:
## Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.

data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Helen', 'Ivy', 'Jack'],
    'age': np.random.randint(20, 50, size=10),
    'gender': ['Female','Male','Male','Male','Female','Male','Female','Female','Female','Male']
}
df = pd.DataFrame(data)
print(df)

      name  age  gender
0    Alice   29  Female
1      Bob   42    Male
2  Charlie   26    Male
3    David   37    Male
4      Eve   29  Female
5    Frank   31    Male
6    Grace   47  Female
7    Helen   47  Female
8      Ivy   30  Female
9     Jack   43    Male


## Exercise 5

In [12]:
## Add a new column to the data frame created in question 1, called occupation.
# The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

df['occupation'] = (['Programmer', 'Manager', 'Analyst','Manager','Programmer','Manager','Analyst','Programmer','Analyst','Programmer'])

print(df)


      name  age  gender  occupation
0    Alice   29  Female  Programmer
1      Bob   42    Male     Manager
2  Charlie   26    Male     Analyst
3    David   37    Male     Manager
4      Eve   29  Female  Programmer
5    Frank   31    Male     Manager
6    Grace   47  Female     Analyst
7    Helen   47  Female  Programmer
8      Ivy   30  Female     Analyst
9     Jack   43    Male  Programmer


## Exercise 6


In [13]:
## Select the rows of the dataframe where the age is greater than or equal to 30.

df_filtered = df[df['age'] >= 30]

print(df_filtered)

    name  age  gender  occupation
1    Bob   42    Male     Manager
3  David   37    Male     Manager
5  Frank   31    Male     Manager
6  Grace   47  Female     Analyst
7  Helen   47  Female  Programmer
8    Ivy   30  Female     Analyst
9   Jack   43    Male  Programmer


## Exercise 7

In [14]:
## Convert this dataframe to a csv file and read that csv file, finally display the contents.

df.to_csv("data_ex7.csv", index=False)
df_read = pd.read_csv("data_ex7.csv")
print("\n Data \n", df_read)


 Data 
       name  age  gender  occupation
0    Alice   29  Female  Programmer
1      Bob   42    Male     Manager
2  Charlie   26    Male     Analyst
3    David   37    Male     Manager
4      Eve   29  Female  Programmer
5    Frank   31    Male     Manager
6    Grace   47  Female     Analyst
7    Helen   47  Female  Programmer
8      Ivy   30  Female     Analyst
9     Jack   43    Male  Programmer
